services:
  db:
    image: postgres:16
    container_name: torneo_db
    environment:
      POSTGRES_USER: torneo_user
      POSTGRES_PASSWORD: torneo_pass
      POSTGRES_DB: torneo_db
    ports:
      - "5432:5432"
    volumes:
      - torneo_pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    container_name: torneo_db_test
    environment:
      POSTGRES_USER: torneo_test_user
      POSTGRES_PASSWORD: torneo_test_pass
      POSTGRES_DB: torneo_test_db
    ports:
      - "5433:5432"
    volumes:
      - torneo_pgdata_test:/var/lib/postgresql/data

  api:
    build: .
    container_name: torneo_api
    environment:
      DATABASE_URL: postgresql://torneo_user:torneo_pass@db:5432/torneo_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  torneo_pgdata:
  torneo_pgdata_test: