apiVersion: v1
kind: Secret
metadata:
  name: torneo-api-secrets
  namespace: torneo-api
type: Opaque
stringData:
  DATABASE_URL: postgresql://torneo_user:torneo_pass@host.docker.internal:5432/torneo_db
